# MySQL8 설정
spring:
  datasource:
    username: root
    password: beaverking

app:
  jwt:
    secret-key: 코카콜라마식따
    time-to-live: 1_800_000 # [millis]
    token-prefix: Bearer
    header-string: Authorization

