key:
  imgUrl: /C:/Users/ys2li/imgPath
  imgPath: /C:/Users/ys2li/imgPath

spring:
  mvc:
    converters:
      preferred-jason-mapper: gson

  profiles:
    active: prod

  config:
    import:
      - classpath:/app/security/security.yml

  jpa:
    generate-ddl: true
    database: mysql
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 200MB
      enabled: true
      max-request-size: 50MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oneday?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul

server:
  servlet:
    encoding:
      charset: utf-8


