key:
  imgUrl: /C:/Users/demisoda/imgPath
  imgPath: /C:/Users/demisoda/imgPath

spring:
  config:
    import:
      - classpath:/app/security/security.yml

  profiles:
    active: prod

  mvc:
    converters:
      preferred-jason-mapper: gson

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oneday?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    hikari:
      connectionTimeout: 10000
      idleTimeout: 600000
      maximum-pool-size: 300
      minimum-idle: 5
      maxLifetime: 10000
      leak-detection-threshold: 2000

  jpa:
    generate-ddl: true
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 200MB
      enabled: true
      max-request-size: 50MB



server:
  servlet:
    encoding:
      charset: utf-8



